# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'f1results (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :ios, '14.1'

  # Pods for f1results (iOS)
  pod 'shared', :path => '../shared'
  
  pod 'MapboxMaps', '10.2.0'
  pod 'BottomSheetSwiftUI'
end

target 'f1results (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  platform :macos, '10.14'

  # Pods for f1results (macOS)
  pod 'shared', :path => '../shared'
end
